### ISSUE TITLE
Initial conditions in polar coordinates

### ISSUE THREAD

**Issue by wfrgra** [natecraddock/projectile#11]
Thanks for developing this addon, it was very handy. 
Any chance you could give the option to specify the initial velocity with polar coordinates?

**Comment by natecraddock** [comment]
Glad it's been helpful :)

Yeah, I can add that, would something like this be what you are hoping for?
![Spherical Coordinates from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/3D_Spherical.svg/240px-3D_Spherical.svg.png)

**Comment by wfrgra** [comment]
Yep, that's it. Thanks

**Comment by natecraddock** [comment]
Okay, I've added the feature. I pushed the changes to master already. Check the `Spherical` box above the velocity input to toggle. Let me know if it works, and if there is anything to change.
