### ISSUE TITLE
No longer drawing trajectories (in Blender 4.0)

### ISSUE THREAD

**Issue by XepherXero** [natecraddock/projectile#21]
The addon no longer draws the trajectory path since updating to Blender 4.0.

**Comment by XepherXero** [comment]
Sorry here is the output from Mac Terminal, seems to be the same error repeating over and over.

[Terminal Saved Output.txt](https://github.com/natecraddock/projectile/files/13444825/Terminal.Saved.Output.txt)

**Comment by natecraddock** [comment]
Sorry for the delay on replying. Looks like this should be a simple fix. Thanks for reporting! I'll work on it soon

**Comment by natecraddock** [comment]
I just pushed some fixes and made a new release. It fixed the issue for me, let me know if that worked for you!

**Comment by XepherXero** [comment]
Hey Nate, it's working for me now. Thank you so much!

<img width="558" alt="image" src="https://github.com/natecraddock/projectile/assets/102024778/682b02ba-d4f2-4e7c-a4bc-f1efefeb8ac3">

**Comment by natecraddock** [comment]
Good to hear! You're welcome!
