### ISSUE TITLE
Use Current for multiple selected objects.

### ISSUE THREAD

**Issue by kurzemnieks** [natecraddock/projectile#3]
If multiple objects are selected and you press "Use Current" for location and rotation is pressed, It does that only for the active object and when you press "Update All" - all objects are put in the same location as active object. 
This seems like a missing functionality to work with multiple selected objects. 

(My use case - I have hundreds of objects scattered around the scene. I can't manually select them one by one and press "Use current" for each. It would be nice if that could be done with one button.)

**Comment by natecraddock** [comment]
Thanks for reporting the bug! Sorry it took so long to fix!
