### ISSUE TITLE
Remove Object Context Error

### ISSUE THREAD

**Issue by isaacdchan** [natecraddock/projectile#7]
1) 'Add Object' under Projectile menu
2) Delete 'Rigid Body' physics under Properties/Physics
3) 'Remove Object' under Projectile menu
4) ![image](https://user-images.githubusercontent.com/33741008/50743556-47f9d000-11ce-11e9-8515-af2667fd870b.png)
 - Unable to 'Remove Object'

Not impactful during use. To bypass just re-add rigid body, remove object, remove rigid body

In case someone runs into this problem when trying to remove object when already removed rigid body first.

**Comment by natecraddock** [comment]
Fixed. Thanks for reporting!
