### ISSUE TITLE
Collision issues

### ISSUE THREAD

**Issue by meljehn** [natecraddock/projectile#9]
Hi,
I have been using a cube projectile to hit a sphere. The goal is for the sphere to behave like a ball that has been hit with something.

However, the collision between the cube and the sphere does not look very convincing. In the attached blend_file, if the angular velocity for the cube is set to (0, 0, 0) the cube gets spin from the ball, but the ball does not rotate until it bounces off the ground. It bounces in the same direction it came from, which would suggest, that the sphere did get some spin from the collision with the cube. Still it should visibly rotate before it hits the ground. 
If the angular velocity of the cube is changed to (20, 10, 5) then the ball behaves the same but the cube's rotation is not affected by the collision with the ball which is strange.
If the angular velocity is set to (20, 10, 90) then the cube starts to rotate slightly after the collision with the ball and the ball bounces off the ground in a totally different direction than before.
Now if the linear velocity of the cube is set to (-130, -150, -40) (basically multiplied by 10), then the cube passes right through the ball without affecting it. It also passes straight through the passive ground plane.

How can I get the cube to hit the sphere and make it rotate like a ball would if it were kicked? And how can I increase the linear velocity of the projectile to several hundred m/s without the cube passing right through other rigid body objects?

I appreciate any input that could help me with this issue.

This contains the blend file:
[scene_0.zip](https://github.com/natecraddock/projectile/files/3574999/scene_0.zip)

**Comment by natecraddock** [comment]
This addon is not meant to be a perfect solution to physics problems, it is actually a rather "hacky" fix. All Projectile can do is keyframe an object, then after the motion is added, enable rigid body physics to continue the motion.

Sadly, this leads to some strange behavior, like in your scene where the cube is trying to hit the sphere. In the range of frames where it should make contact, the cube is still controlled by the animation system, this leads to some very strange behaviors.

My suggestions to fix the scene:
- I'm not sure why you are changing gravity to be -y.. You can go for it for sure, I'm just not sure if there are strange implications.
- Try to scale things up. Blender struggles with small objects and rigid bodies. Or turn up the quality in the Projectile settings.
- You could also move the sphere a bit farther from the cube, or the cube farther from the sphere, to give the cube time to travel with it's initial velocity.
- Depending on what you are creating, it may be better to just animate this manually.

I hope those ideas help. I have a few more features I want to add to Projectile when I have the time that might increase stability, but not by much. Sorry there isn't much more I can do for you, and sorry for the late reply. Good luck!
